// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtislgdvjizvnejazhwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aXNsZ2R2aml6dm5lamF6aHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjgyNzEsImV4cCI6MjA2Nzg0NDI3MX0.L7B4CiRmXu3WD6Jba5M7zZpb3x5JKKRzv6z36lAGj-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});